### ISSUE TITLE
Port setup.py to GTK+ 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/MathGraph32#6]
`activity.py` uses GTK+ 3 Sugar Toolkit, but `setup.py` uses GTK+ 2 Sugar Toolkit.

**Comment by yell0wfl4sh** [comment]
@quozl this issue can be closed now.

**Comment by quozl** [comment]
@yashagrawal3, you abbreviated "Fixes" in https://github.com/sugarlabs/MathGraph32/pull/8 so in future please use a separate line, e.g.

```
fixes #5
fixes #6
```

**Comment by yell0wfl4sh** [comment]
sure!
